<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Uninstall from apps and sales channel settings page</name>
   <tag></tag>
   <elementGuidId>c6b9b661-b15f-4949-be7b-ba124a6feecb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'Polaris-Button_r99lw Polaris-Button--primary_7k9zs Polaris-Button--destructive_zy6o5' and @type = 'button' and (text() = 'Uninstall' or . = 'Uninstall')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[25]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.Polaris-Button_r99lw.Polaris-Button--primary_7k9zs.Polaris-Button--destructive_zy6o5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dc9101d5-291a-49a5-9d51-25d6fa090225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Polaris-Button_r99lw Polaris-Button--primary_7k9zs Polaris-Button--destructive_zy6o5</value>
      <webElementGuid>105a4ece-4397-47ca-bb58-ebb7753aa809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>771ecfe3-ea23-4243-80dd-3c373f932edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6b674c03-ee3a-4fc9-a810-07bc6009adbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Uninstall</value>
      <webElementGuid>ae9a307f-1f9d-47b2-ab2e-c201c0fed3af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PolarisPortalsContainer&quot;)/div[19]/div[1]/div[@class=&quot;Polaris-Modal-Dialog__Container_13mbo&quot;]/div[1]/div[@class=&quot;Polaris-Modal-Dialog_n3qgo&quot;]/div[@class=&quot;Polaris-Modal-Dialog__Modal_2v9yc&quot;]/div[@class=&quot;Polaris-HorizontalStack_dv6q6&quot;]/div[@class=&quot;Polaris-Box_375yx&quot;]/div[@class=&quot;Polaris-HorizontalStack_dv6q6&quot;]/div[@class=&quot;Polaris-HorizontalStack_dv6q6&quot;]/button[@class=&quot;Polaris-Button_r99lw Polaris-Button--primary_7k9zs Polaris-Button--destructive_zy6o5&quot;]</value>
      <webElementGuid>8059bb37-760c-4d27-bed2-9d0cce7591fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[25]</value>
      <webElementGuid>2cb69d5d-0fb6-4d4b-8736-f44e23d1383f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PolarisPortalsContainer']/div[19]/div/div/div/div/div/div[3]/div/div/div[2]/button[2]</value>
      <webElementGuid>dcc782c7-11ac-4436-9339-4845f6bdc5e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>77aaab1c-76b8-40b5-87bd-eaeb23a52899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[2]/following::button[2]</value>
      <webElementGuid>5a04853f-e8aa-4188-933f-bd1eb0c74371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>b1985f04-3195-419a-9e55-483413fd55b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
